version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: app_frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"
  mysql:
    build:
      dockerfile: Dockerfile
      context: ./mysql
    restart: unless-stopped
    container_name: app_mysql
    ports:
      - "3304:3306"
    volumes:
      - ./mysql/mysql_data:/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_HOST: "localhost"
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3304
